

services:

  db:
    image: postgres:15.10
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./script/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "15432:5432"

  redis:
    image: "bitnami/redis:latest"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
        - "16379:6379"

  etcd:
    image: "bitnami/etcd:latest"
    restart: always
    environment:
        - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "12379:2379"
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017