---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hwxwa.
--- DateTime: 2025/3/10 12:56
---

local key = KEYS[1]
local cntKey = ARGV[1]
local delta = tonumber(ARGV[2])

local exists = redis.call('exists', key)
if exists == 1 then
    redis.call("hincrby", key, cntKey, delta)
    return 1
else
    return 0
end